### ISSUE TITLE
Session cookies not present in file download requests

### ISSUE THREAD

**Issue by alan-grixti** [silkimen/cordova-plugin-advanced-http#57] opened 2018-01-03 15:43 UTC
Hi,

I am using the plugin for downloading files from a secured endpoint via HTTP only session cookies. Any requests following the login work and do forward any session cookies set. However, this does not seem to be the case when it comes to file download requests.

**Comment by silkimen** [comment] 2018-01-04 03:17
Hi alan,

I wrote two specs to reproduce your problem ([see here](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/app-test-definitions.js#L317-L366)). But I don't face the problem you have mentioned.

Is it possible to get access to your endpoint? I'd like to test against your backend.

**Comment by alan-grixti** [comment] 2018-01-04 08:05
Hi Sefa,

Thanks for your response, Unfortunately the backend is not accessible. However I can give you more information as you wish. I have one quick question to ask though.  I see in your specs that you are setting the cookies manually. Is this the default behavior, or are any cookies set prior to the specific request expected to be forwarded automatically? As this is the behavior I am seeing when performing a get request.

The backend is written in C#, .NET Core 2.0  Web API project. The assigning of cookies is being done as per the snippet below. The `services` object is an instance of `IServiceCollection services` (as per the Web API guidelines).

`services.AddSession(options =>
            {
                options.Cookie = new CoreCookieBuilder()
                {
                    Name = "MySession",
                    HttpOnly = true
                };
                options.IdleTimeout = TimeSpan.FromMinutes(30);
                options.IOTimeout = TimeSpan.FromSeconds(30);               
            });`

Thanks a lot!

**Comment by silkimen** [comment] 2018-01-04 12:04
> I have one quick question to ask though. I see in your specs that you are setting the cookies manually. Is this the default behavior, or are any cookies set prior to the specific request expected to be forwarded automatically? As this is the behavior I am seeing when performing a get request.

I'm setting the cookies manually, just because it's easier for implementing the specs. But of course default behavior is to handle "Set-Cookie" headers received from server and to automatically forward them on following requests.

> When I call cordova.plugin.http.getCookieString on my endpoint I can find and see the cookies set in place. Is there some way I can monitor what is happening on a deeper level? I am doing my development through Chrome's web inspector, however these details are not present at this level.

You can start your app via XCode or Android Studio depending on the platform you are developing for and set breakpoints in the native code.

To see if the cookie header is passed to the native code:
- iOS: set a breakpoint [here in line 389](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/ios/CordovaHttpPlugin.m#L389)
- Android: set a breakpoint [here in line 27](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/src/android/com/synconset/cordovahttp/CordovaHttpDownload.java#L27)

 Btw: which platforms are affected by this issue?

**Comment by alan-grixti** [comment] 2018-01-04 13:33
Fantastic support, will look into it asap and get back to you. So far I've only tested on Android. Will keep you posted about iOS.

Thanks once again!

**Comment by silkimen** [comment] 2018-02-06 13:23
Closing this, feel free to open a new issue (referencing this one), if this won't solve your problem!

**Closed by silkimen** 2018-02-06 13:23 UTC
Labels: need more info
