### ISSUE TITLE
Debugging Network Requests When Using cordova.plugin.http

### ISSUE THREAD

**Issue by ofirattia** [silkimen/cordova-plugin-advanced-http#388] opened 2020-12-08 20:28 UTC
Hi,
There is any option to debug the calls that being called using cordova.plugin.http on the developer tools? like any other XHR?

Because if I am using the cert pinning for example, I want to see the network calls as well, as of now I am not able to see them.

**Comment by ofirattia** [comment] 2020-12-08 20:30
I am closing since its duplicate and there is no option to do that.

**Comment by silkimen** [comment] 2020-12-29 16:16
Hi @ofirattia, you are right, this is a duplicate of #167. Unfortunately, not possible in developer tools.

**Closed by silkimen** 2020-12-29 16:16 UTC
Labels: duplicate, question
