### ISSUE TITLE
Allow setting request specific serializer

### ISSUE THREAD

**Issue by darkyen** [silkimen/cordova-plugin-advanced-http#77] opened 2018-02-16 21:53 UTC
Hi I am currently authoring a library using this plugin. I do not want to `setSerializer` and default break all other functionality. While for most apps `json` is acceptable, I don't think forcing a global serializer is a good option in long run. It'd be awesome if you could add support for a serializer in the plugin, at the moment i am using the serializer `utf8`

**Comment by silkimen** [comment] 2018-02-27 14:04
Hi darkyen, can you please explain your use case more in detail? Do you want a possibility to add custom serializers? Or do you want a possibility to override the global serializer for a single request?

**Comment by chax** [comment] 2018-02-27 14:55
I think he means to override global serializer. But this isn't the problem only with serializer, the problem is for all settings that are set up globally. For example setRequestTimeout is also global setting, and it would also be nice to be able to specify it per request.

**Comment by silkimen** [comment] 2018-02-27 16:50
Well, I could expose serializer and timeout for every single request, so you can override it. But this would be a major (breaking) change. Could be implemented like this maybe:

```js
const options = {
  timeout: 10,
  headers: {},
  serializer: cordova.plugin.http.serializer.JSON
  // ... and other options (all of them optional)
};

cordova.plugin.http.get(url, requestParams, options, resolve, reject);
cordova.plugin.http.post(url, data, options, resolve, reject);
```

@darkyen, @chax: What do you think?

**Comment by darkyen** [comment] 2018-02-27 17:00
My use case is that as a library author I don't want to pollute the global settings as the end application may or may not be using the same serialization as I am. Your suggestions is exactly what I was looking for, being able to pass the serializer dynamically will allow this to be shared with the application without having another copy :).

**Comment by chax** [comment] 2018-02-27 17:16
Yes, but this would break Backwards Compatibility, especially since your plugin is used in ionic and there is ionic wrapper written for it. But with this "options" parameter, you could later add whatever to it, without breaking Backwards Compatibility.

**Comment by darkyen** [comment] 2018-02-27 17:17
You could just keep global and allow request overrides, that won't break any compability.

**Comment by chax** [comment] 2018-02-27 17:26
@darkyen, you didn't understand my point, it WOULD break Backwards Compatibility for those who use ionic wrapper.

**Comment by chax** [comment] 2018-02-27 17:27
See this: https://ionicframework.com/docs/native/http/

**Comment by darkyen** [comment] 2018-02-27 17:30
From https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/http/index.ts it looks like the "wrapper" is more of a typedef.

**Comment by chax** [comment] 2018-02-27 18:06
You are right on that. But then we need to update wrapper also.

**Comment by silkimen** [comment] 2018-02-27 18:06
@darkyen Basically you're right. They should rely on a specific version, but as far as I know they don't. I don't know, if there is a possibility to check for the major version of this plugin and expose another Interface. So this could be a problem.

**Comment by darkyen** [comment] 2018-02-27 18:09
Ouch, so the only option that remains is to have code like 

```javascript
if (arguments.length === 5) {
    // merge options here 
} else { 
    // Use the old style.
}
```

This will ease the upgrade path.

**Comment by silkimen** [comment] 2018-02-27 18:12
Yes, I have already written some backwards compatibility code like your example (see [advanced-http.js#L56-L64](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/advanced-http.js#L56-L64)). But it's really a pain in the ass to maintain such code :/

**Comment by darkyen** [comment] 2018-02-27 18:26
@silkimen It definitely is, I understand your problem here, but technically Ionic or any modern project _shouldn't_ be doing non-versioned deployments. The bigger problem here is that in the current state the plugin cannot talk into more than 1 serialization, timeout setting. Which may or may not be applicable globally. 

Say for example my plugin talks in JSON, another one maybe talking in and some in URLEncoded to 3rd party APIs. If they both were to be used, they'll become mutually incompatible. Or for example have requests with 1 and 10 second timeout in the same app. 

Since this plugin is applicable on WKWebView its even more of a problem from an application developers point of view that is using the library, and another library can be using this. Because these global flags will not be obvious and much harder to debug. Alternatively, I'll need to bake 2 versions of the same lib or increase the package size by adding our custom version of networking layer that achieves the same key goals as this library.

**Comment by silkimen** [comment] 2018-02-27 18:26
I'd like to discuss this topic more in detail. Would you mind joining my slack workspace?
 https://join.slack.com/t/ilkimen/shared_invite/enQtMzIxODY2NzM0ODUzLTlhOTc1ZDZmMjE0OThhODgwNGNhYjBlYTdmNjY2NjcwNTJjMGQ0MzE0MTM5MTJhYWZhM2MwOTAwNDBlMjU3M2E

**Comment by silkimen** [comment] 2018-02-28 03:13
Found a way to implement this feature without breaking backwards compatibility. I have implemented one function for all types of HTTP requests and the existing API is using this function.

@darkyen So you can use the new function "sendRequest", whereas ionic native will stick to the "old" API using the shorthand functions. I hope this meets your requirements!

Will be included in upcoming version 1.11.0.

**Comment by chax** [comment] 2018-02-28 12:42
This is awesome. Good solution @silkimen

**Comment by silkimen** [comment] 2018-03-02 00:12
Closing this, feel free to open a new issue, if this won't solve your problem!

**Closed by silkimen** 2018-03-02 00:12 UTC
Labels: feature
