### ISSUE TITLE
plugin_not_installed error with ionic

### ISSUE THREAD

**Issue by jeandesma** [silkimen/cordova-plugin-advanced-http#8] opened 2017-08-30 15:12 UTC
Hello,

I am trying to use this plugin on a ionic project. I installed it the way the ionic native doc told me to which is: 

    $ ionic cordova plugin add cordova-plugin-advanced-http
    $ npm install --save @ionic-native/http

Then I used it as follow in my provider:

     constructor( @Inject(EnvVariables) public envVariables, public correspondanceProvider: CorrespondanceProvider, public http1: HTTP, private platform:Platform) {
        this.platform.ready().then(
          () => {
            this.http1.validateDomainName(false);
          }
        );
      }

But as soon as my provider is called I get the error: 
2017-08-30 17:03:26.520184+0200 MyApp WARN: Native: tried calling HTTP.post, but the HTTP plugin is not installed.
2017-08-30 17:03:26.520338+0200 MyApp WARN: Install the HTTP plugin: 'ionic cordova plugin add cordova-plugin-advanced-http'

But I have:
> cordova plugin ls
✔ Running command - done!
cordova-plugin-advanced-http 1.5.9 "Advanced HTTP plugin"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-screen-orientation 2.0.1 "Screen Orientation"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.8 "BarcodeScanner"

Is there another way to install the plugin or am I doing something wrong?

Thanks 

Ionic info:
cli packages:

    @ionic/cli-utils  : 1.6.0 (/Users/jde/Documents/Fork/PRI1701/appliPrintemps/node_modules/ionic/node_modules/@ionic/cli-utils)
    ionic (Ionic CLI) : 3.6.0 (/Users/jde/Documents/Fork/PRI1701/appliPrintemps/node_modules/ionic)

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    npm        : 3.10.10

**Comment by silkimen** [comment] 2017-08-30 15:46
Hi jeandesma,

actually I didn't even know that our plugin is used in ionic native. I think the problem is situated in how the project is integrated in ionic native. I'll set up a little demo project to find the problem.

**Comment by silkimen** [comment] 2017-08-31 00:54
Ok, found the issue. It's already fixed on master branch, but I don't know when it will be released. See this link for more info https://github.com/ionic-team/ionic-native/pull/1921

Please consult the ionic team for further assistance, because this is not a problem of this project.

**Comment by jeandesma** [comment] 2017-08-31 13:53
You are right, changed the wrapper and everything is working fine now. Thanks a lot!

**Closed** 2017-08-31 13:54 UTC

**Comment by shadoWalker89** [comment] 2017-09-04 12:54
@jeandesma How did you solve this ?
I'm still getting the same error as you did when installing the plugin at this very moment

**Comment by jeandesma** [comment] 2017-09-04 13:51
https://github.com/ionic-team/ionic-native/pull/1934/commits/49ee0d85a304770a9a3bd3e04eb9609e6d565b67

As a quick fix you might just fix the reference error yourself. Just do what is done in this commit and it will work fine.

**Comment by shadoWalker89** [comment] 2017-09-04 14:10
Thanks jeandesma, everything is working fine now.

**Comment by matodrobec** [comment] 2017-09-28 13:27
@shadoWalker89  I fix  this like https://github.com/ionic-team/ionic-native/pull/1934#issuecomment-331861871 . It is working well to me

**Comment by shadoWalker89** [comment] 2017-09-30 10:51
@matodrobec Thanks for sharing, but i found out that using the angular http and now the angular HttpClient is far more better for my needs.
The Interceptors are a life savior in angular.
Also it is important to me that i see the requests and responses in my network tab of the browser, but with the native solution you cannot to that because the requests and responses are made on the device directly on the browser has no idea about them.

**Comment by yaozuwang** [comment] 2017-10-30 01:12
I am still getting this error, the reference is fine

**Comment by icenevins** [comment] 2017-10-31 08:39
I got the same problem too. I think it's solved

**Comment by yibsonalexis** [comment] 2018-11-01 03:43
Hello.
This solves your problem.

Before your petition.

this.http.setSSLCertMode(‘nocheck’).then((resp: any) => {
console.log(resp);
}, (error) => {
console.log(error);
});

**Comment by AshvinMani** [comment] 2019-04-04 05:55
I have the same issue still not working plugin ref also changed as done in the commit
