### ISSUE TITLE
[Bug] [ionic] http plugin conflict with ionic icons on Android 5.0 or 5.1

### ISSUE THREAD

**Issue by SSuarezBrooktec** [silkimen/cordova-plugin-advanced-http#309] opened 2020-02-13 16:03 UTC
**Describe the bug**
http plugin on Ionic 4 conflict with ionicons on **Android 5.0 or 5.1**
If i **remove  cordova-plugin-file and after run ionic cap run android** (works properly)

But the problem is when in android i execute this command: ### ionic cap update android
cli say this: **[info] installing missing dependency plugin cordova-plugin-file**
and the app is broken again

**System info**
-  "cordova-plugin-advanced-http": "^2.4.0"

**Are you using ionic-native-wrapper?**
 -     "@ionic-native/http": "^5.21.5"
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem? Yes and they scale the issue to this plugin, you can check here: https://github.com/ionic-team/ionic/issues/20304

**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.
<ion-icon name="ios-arrow-back"></ion-icon>

You can check this repo: https://github.com/SSuarezBrooktec/Ionic_4_Android_5_ionicons_Error

**Ionic info:**

```
 Android SDK Tools : 26.1.1 (/Users/sergio/Library/Android/sdk)
   NodeJS            : v13.0.1 (/Users/user/.nvm/versions/node/v13.0.1/bin/node)
   npm               : 6.13.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504
```

Here package.json

```
  "dependencies": {
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@capacitor/android": "^1.4.0",
    "@capacitor/core": "1.4.0",
    "@capacitor/ios": "^1.4.0",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@ionic-native/core": "^5.20.0",
    "@ionic-native/fingerprint-aio": "^5.20.0",
    "@ionic-native/http": "^5.20.0",
    "@ionic-native/keyboard": "^5.20.0",
    "@ionic-native/screen-orientation": "^5.20.0",
    "@ionic/angular": "^4.11.10",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@ng-idle/keepalive": "^8.0.0-beta.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/jwt-decode": "^2.2.1",
    "angular-highcharts": "^8.0.3",
    "capacitor-fcm": "^1.0.0",
    "capacitor-secure-storage-plugin": "^0.3.0",
    "classlist.js": "^1.1.20150312",
    "cordova-plugin-advanced-http": "^2.4.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-fingerprint-aio": "^3.0.1",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "core-js": "2.5.7",
    "es6-promise-plugin": "^4.2.2",
    "highcharts": "^7.2.1",
    "i18n-iso-countries": "^4.3.1",
    "jwt-decode": "^2.2.0",
    "ng2-fittext": "^1.2.8",
    "ngx-currency": "^2.2.2",
    "rxjs": "~6.5.4",
    "rxjs-compat": "^6.5.4",
    "tslib": "^1.10.0",
    "validator": "^12.1.0",
    "web-animations-js": "^2.3.2",
    "whatwg-fetch": "^3.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.23",
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular-devkit/core": "^8.3.23",
    "@angular-devkit/schematics": "^8.3.23",
    "@angular/cli": "^8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@capacitor/cli": "1.4.0",
    "@ionic/angular-toolkit": "^2.1.2",
    "@types/big.js": "^4.0.5",
    "@types/jasmine": "~3.4.6",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "~8.10.59",
    "codelyzer": "^5.2.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "protractor": "~5.4.2",
    "ts-node": "~7.0.1",
    "tslint": "~5.20.1",
    "typescript": "~3.5.3"
  }
```

**Screenshots**
Here 2 screenshots, (working and error)

<img width="190" alt="Captura de pantalla 2020-01-28 a las 23 39 48" src="https://user-images.githubusercontent.com/56263935/73312225-81154000-4228-11ea-9f74-44221ca0b1cb.png"> <img width="200" alt="Captura de pantalla 2020-01-28 a las 23 08 44" src="https://user-images.githubusercontent.com/56263935/73312227-82466d00-4228-11ea-8073-25277a50ebd2.png">

**Comment by SSuarezBrooktec** [comment] 2020-02-18 12:00
How about?

**Comment by silkimen** [comment] 2020-02-20 01:18
Your problem is caused by cordova-plugin-file, which is indeed an dependency of this plugin. But it‘s nothing I can fix here. Removing that dependency is an option, but see #238 for details.

**Comment by SSuarezBrooktec** [comment] 2020-02-28 21:36
So the only solution is to delete the plugin file for Android? 
The problem is that I need is the plugin for live updates :(

**Comment by silkimen** [comment] 2020-06-25 05:51
Closing this, feel free to open a new issue, if this won't solve your problem! 👍

**Closed by silkimen** 2020-06-25 05:51 UTC
