### ISSUE TITLE
[Bug] [iOS] clearCookies does not work 

### ISSUE THREAD

**Issue by gabrielepmattia** [silkimen/cordova-plugin-advanced-http#248] opened 2019-08-18 12:36 UTC
**Describe the bug**
When a request response has the header `set-cookie` the cookie is correctly set and then retrieved with `getCookieString()`. When `clearCookies()` is called the cookie is no more available with `getCookieString()` but persists in next http calls. Behavior is correct on Android.

**System info**
 - affected HTTP plugin version: 2.1.1
 - affected platform(s) and version(s): iOS 12.4
 - affected device(s): Simulator and physical device
 - cordova version: 5.2.5
 - cordova platform version(s): ios 5.0.1, android 8.0.0

**Are you using ionic-native-wrapper?** Yes.
 - ionic-native-wrapper version: 5.12.0
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem? Yes, no one reported the problem.

**Minimum viable code to reproduce**

I wrote a basic app with 4 buttons and a mini webserver which basically set a cookie (with a GET to `/set-cookie` path) and print the request cookie headers (with a GET to `/`).

- App: https://github.com/gabrielepmattia/ionic-cookie-test
- Server code: https://gist.github.com/gabrielepmattia/f9f6f4ce5e3312590e24e2631bc7a638

For reproducing, add the iOS platform then build and run on device. Press the buttons in sequence from top to bottom, the last result should be empty. (I also used this app for testing the browser behavior, and the cookie is not even set -- maybe is convenient to open another issue for describing this inconsistent behavior between platforms)

**Screenshots**
None

**Comment by FredCote** [comment] 2019-08-26 12:52
Same problem here.... tried everything no result so far....

**Comment by arjel** [comment] 2019-10-04 09:15
Same here ... @gabrielepmattia, @FredCote have you found a solution?

**Comment by sbannigan** [comment] 2020-01-21 18:37
I'm pretty sure this change is what is causing this to happen: https://github.com/silkimen/cordova-plugin-advanced-http/commit/d444363a8eb4aa08caf4dca92ea857d1343f2208#diff-b9a703dfe2f46d8863e3c89f83b6e96aL161-R185. It seems like if the `Cookie` header is not explicitly overwritten, the last value is still set somewhere else.

**Comment by yazantahhan** [comment] 2020-05-13 07:48
Hi @silkimen,
When do you think this fix will be merged into master?

**Comment by silkimen** [comment] 2020-05-29 02:59
@yazantahhan thanks for reminding me about this one 👍 Will be fixed in v2.5.1.

**Closed** 2020-05-29 03:00 UTC

**Comment by godonovan-jh** [comment] 2020-06-02 14:45
Hi @silkimen, Just wondering if v2.5.1 is close to being ready? I see the code checked in, hoping to pull it in via NPM. The clearCookie fix is of interest to my project. Thank you!

**Comment by silkimen** [comment] 2020-06-03 23:39
Just released now 🙂

**Comment by kanongil** [comment] 2020-06-18 08:40
This "fix" broke my code, which relies on cookies being stored at the OS level…

**Comment by johnborges** [comment] 2020-09-17 15:39
As of version 3.0.0 of this plugin I can confirm this issue still exists. What worked for me was to use another separate plugin that cleared cookies in `HTTPCookieStorage.shared`.

**Comment by achakra21** [comment] 2021-02-22 05:07
@johnborges Seems the issue still persists on 3.1.0 , but what was that plugin you have used to cleared the cookies

**Comment by johnborges** [comment] 2021-02-22 14:02
@achakra21 [capacitor-plugin-cookies](https://github.com/johnborges/capacitor-plugin-cookies)

**Comment by achakra21** [comment] 2021-02-23 02:58
@johnborges thanks for the your quick reply ,I found a way this clearCookies() to work on iOS , I was using in on ionViewDidLoad() it was not working but same was working with Android , but in my use case when I next time logging in to the App it should clear the previous cache cookies , so I added the clearCookies() method inside the login method now it seems to be working on iOS , but still I don't know why it's works here inside login method why not in ionViewDidLoad() 😇

**Comment by achakra21** [comment] 2021-03-02 02:26
I can confirm now it's working with recent version on iOS 13 and 14  ,it's sometimes not works if you place it inside the life cycle method , but it works if you place inside and button click method , in my case I had to clear the cookies each time I login ,  I placed the clearCookies() method inside that it worked .
