### ISSUE TITLE
[Bug] [iOS] cannot use number in parameter value

### ISSUE THREAD

**Issue by afulkersonApollo** [silkimen/cordova-plugin-advanced-http#406] opened 2021-03-24 15:37 UTC
**Describe the bug**
When using params, the value cannot be a number or sendRequest will throw an error.

**System info**
 - affected HTTP plugin version: latest
 - affected platform(s) and version(s): iOS 14.4
 - affected device(s): iPhone 12 Max
 - cordova version: latest
 - cordova platform version(s): latest

**Minimum viable code to reproduce**
```js
const params = { "userId": 123 }; // this causes the plugin to throw an error unless you use toString() on the value first
cordova.plugin.http.sendRequest(url, { method: 'get', params });
```

**Comment by silkimen** [comment] 2021-07-07 02:41
Yep, true this is intended behavior. It's meant to be type safe and it's up to you to convert your data.

**Comment by silkimen** [comment] 2021-08-20 01:20
Closing this, feel free to open a new issue, if this won't solve your problem! 👍

**Closed by silkimen** 2021-08-20 01:20 UTC

**Comment by CodeWithOz** [comment] 2021-12-01 15:48
Wow, this is quite a restriction. Fair enough that type safety is the reason but at least it should be stated clearly in the docs as a warning that devs should be aware of before they start using the plugin.

**Comment by CodeWithOz** [comment] 2021-12-01 16:30
Is it possible to add the option of a custom serializer? I have one that I used before this plugin but it fails because `checkKeyValuePairObject` requires that the original data be an object. How about allowing us to just pass in the stringified params if we've already serialized it? It's quite cumbersome to have to change individual values to strings just to make things work with this plugin.

**Comment by CodeWithOz** [comment] 2021-12-01 18:52
I got around this by serializing my request params and adding the serialized string directly to the url instead of putting them in the `params` object, because that's what this plugin eventually does after processing the params. For anyone wondering how to serialize your query params, you can either use this plugin's serializer in the [`url-util.js file`](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/url-util.js), or you can use your own (I use [this one](https://stackoverflow.com/a/54958859/7987987)).
