### ISSUE TITLE
ERROR no such file or directory www/umd-tough-cookie.js

### ISSUE THREAD

**Issue by kevinhuron** [silkimen/cordova-plugin-advanced-http#7] opened 2017-08-28 15:32 UTC
Hi !

I got a **no such file or directory www/umd-tough-cookie.js** when I try to install this plugin in my Ionic app...

Thank's

Cordially

**Comment by silkimen** [comment] 2017-08-28 16:24
Can you provide me some more info? Which version are you trying to install? Which command did you use to install? And complete error output, please.

**Comment by kevinhuron** [comment] 2017-08-28 16:36
Yes ! really sorry...

I'm using the latest version of ionic and ionic native and I was waiting for an update to their plugin http, which, thanks to you is finally better.

I'm trying to install your lastest version of your plugin.

**IONIC INFO** : 

    cli packages: (/usr/local/lib/node_modules)
           @ionic/cli-utils  : 1.9.2
           ionic (Ionic CLI) : 3.9.2
    global packages:
           Cordova CLI : 7.0.1 
    local packages:
          @ionic/app-scripts : 2.1.4
          Cordova Platforms : android 6.1.2 ios 4.3.1
          Ionic Framework : ionic-angular 3.6.0
    System:
          Android SDK Tools : 25.2.5
          ios-deploy        : 1.9.1 
          Node           : v7.1.0
          npm               : 4.5.0 
          OS                : macOS Sierra
          Xcode             : Xcode 8.3.3 Build version 8E3004b

And this is what I have tried : 
**cordova plugin add https://github.com/silkimen/cordova-plugin-advanced-http --save**
this give me this output : 

        ✖ Running command - failed!
        [ERROR] An error occurred while running cordova plugin add 
        https://github.com/silkimen/cordova-plugin-advanced-http 

        --sa... (exit code 1):
        
        Installing "cordova-plugin-advanced-http" for android
        Plugin dependency "cordova-plugin-file@4.3.3" already fetched, using that version.
        Dependent plugin "cordova-plugin-file" already installed on android.
        Error during processing of action! Attempting to revert...
        Failed to install 'cordova-plugin-advanced-http': Error: Uh oh!
        ENOENT: no such file or directory, open 
        '/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/plugins/cordova-plugin-advanced-http/www/umd-tough-cookie.js'
             at Object.fs.openSync (fs.js:557:18)
             at Object.fs.readFileSync (fs.js:467:33)
             at install 
        (/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/lib/pluginHandlers.js:173:36)
             at ActionStack.process 
        (/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
             at PluginManager.doOperation 
        (/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
             at PluginManager.addPlugin 
        (/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
             at /Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/Api.js:254:18
             at _fulfilled 
        (/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/node_modules/q/q.js:834:54)
             at self.promiseDispatch.done 
        (/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/node_modules/q/q.js:863:30)
             at Promise.promise.promiseDispatch 
        (/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/platforms/android/cordova/node_modules/q/q.js:796:13)
        Error: Uh oh!
        ENOENT: no such file or directory, open 
        '/Users/kevinhuron/Documents/ePressPack/mobile-app-v2/eppMobileV2/plugins/cordova-plugin-advanced-http/www/umd-tough-cookie.js'

**Comment by silkimen** [comment] 2017-08-28 16:44
Ah ok, I see the problem. You can not directly install the plugin from the github url. We are running a build task before pushing it to npm. This is the reason the file is missing for you.

Just run `cordova plugin add cordova-plugin-advanced-http` and it should work. If you want to install it from github, you need to pull the latest version and then run `npm run build`.

**Comment by kevinhuron** [comment] 2017-08-28 16:47
Oh Okey !

Thank's you very much

unfortunately I got this : 

     cordova plugin add cordova-plugin-advanced-http --save
    ✖ Running command - failed!
    [ERROR] An error occurred while running cordova plugin add cordova-plugin-advanced-http --
    save (exit code 1):

        
        Error: Failed to fetch plugin git+https://github.com/silkimen/cordova-plugin-advanced-http.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Failed to get absolute path to installed module

**Comment by silkimen** [comment] 2017-08-28 22:54
Hmm ok, I've set up a little demo project with ionic and it's working for me without problems.

Ionic info:
```
cli packages: (/Users/sefa/.nvm/versions/node/v7.4.0/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.1.2 ios 4.3.1
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1 
    ios-sim    : 6.0.0 
    Node       : v7.4.0
    npm        : 4.0.5 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
```

I think your issue is related to connection or registry. Do you use a custom npm registry (e.g. Sonatype Nexus, Artifactory, etc.)? Are you running behind a proxy server?

And it's also strange that it's still trying to download it by Github url. It should fetch the plugin package from npm registry (https://registry.npmjs.org/). Maybe you can try to erase all npm and cordova caches and then retry installation. Did you remove the broken plugin (this one you installed by Github url) before running this command?

**Comment by silkimen** [comment] 2017-09-04 18:44
@kevinhuron I'm closing this issue now, because I can not reproduce your issue. Please feel free to open another one, if you can provide me some more details.

**Closed by silkimen** 2017-09-04 18:44 UTC
