### ISSUE TITLE
[Bug] [platform] url-encoded documentation is wrong

### ISSUE THREAD

**Issue by agomezmoron** [silkimen/cordova-plugin-advanced-http#314] opened 2020-02-26 19:23 UTC
**Describe the bug**
Following the documentation to perform a POST www-url-encoded and it doesn't work. The 'urlencoded' serializer doesn't work and the header is not added. On the other hand, if you define the serializer as UTF8, it adds the Content-Type: application/www-url-encoded header.

**System info**
 - affected HTTP plugin version: 2.4.1
 - affected platform(s) and version(s): iOS and Android

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: 5.21.6
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem? yes

**Minimum viable code to reproduce**
If applicable, add formatted sample coding to help explain your problem.

e.g.:
```js
cordova.plugin.http.setDataSerializer('urlencoded');
```
Fails, but if you add:
```js
cordova.plugin.http.setDataSerializer('urf8');
const httpHeader = {
  'Content-Type':  'application/x-www-form-urlencoded'
};
```
It works.

I don't really know if it's a bug in the code or it works as expected - but if that, a section in the readme is missing alerting about that. I found that at https://stackoverflow.com/questions/55917307/ionic-native-http-post-method-not-working-on-ios-but-perfectly-working-on-andro

**Comment by silkimen** [comment] 2020-03-07 05:03
Hi Alejandro, your proposed code won't transmit URL encoded form data. It will send your data as plain text, but you'll be overriding the `Content-Type` header. Please add a code extract which is NOT working for you. I'll need to reproduce your problem.  There are several tests in the [e2e specs suite](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/test/e2e-specs.js) which are testing this feature.

**Comment by silkimen** [comment] 2020-06-25 01:07
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍

**Closed by silkimen** 2020-06-25 01:07 UTC
Labels: need more info
