### ISSUE TITLE
Error submitting through uploadFile in iOS

### ISSUE THREAD

**Issue by cyof** [silkimen/cordova-plugin-advanced-http#258] opened 2019-10-17 03:47 UTC
I get the following error when submitting file to the server through uploadFile in iOS.

> -[__NSArrayM length]:
> unrecognized selector sent to instance 0x1c46571f0
> *** Terminating app due
> to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM
> length]: unrecognized selector sent to instance 0x1c46571f0'
> *** First throw call stack:
> (0x183866d8c 0x182a205ec 0x183874098 0x18386c5c8 0x18375241c 0x18383c5d8
> 0x1841c2760 0x1841c25e4 0x10411b150 0x10418afc4 0x10414bc84 0x10414baec
> 0x10414dec4 0x19356ad14 0x193507b54 0x193509cc4 0x193271634 0x1934b06d4
> 0x193234618 0x193237020 0x18ae9c148 0x18ae9c408 0x18380f404 0x18380ec2c
> 0x18380c79c 0x18372cda8 0x185711020 0x18d749758 0x104100e5c 0x1831bdfc0)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb) 

Has anyone encountered this before?

**Comment by silkimen** [comment] 2020-01-27 23:25
Please provide some MVP code for reproducing this problem. Which version are you using? Which parameters did you provide? etc.

**Comment by silkimen** [comment] 2020-06-25 05:54
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍

**Closed by silkimen** 2020-06-25 05:54 UTC
Labels: need more info, question
