### ISSUE TITLE
Receiving different structure of data between iOS and Android when using "urlencoded" serializer

### ISSUE THREAD

**Issue by kaceman** [silkimen/cordova-plugin-advanced-http#48] opened 2017-11-23 12:13 UTC
Hello,

I'm having a problem with the post method of the plugin, There is a difference in the data structure sent from the iOS and Android client.
This is the function that sends the post request: 
```
getEventsDetails(eventMemberIds) {
    return new Promise((resolve, reject) => {
      let data = {
        emIds: eventMemberIds
      };
      this.http.post('getEventsDetails', data).then((response: string) => {
        resolve(JSON.parse(response));
      }).catch((err) => reject(err));
    });
  }
```
In the server side this is what I receive:

![image](https://user-images.githubusercontent.com/17954986/33172283-6a4ae1f4-d047-11e7-90a4-af4bd534b27f.png)

**Comment by silkimen** [comment] 2017-11-24 13:25
Hi kaceman,

can you please show me the complete content of `data` before sending it to the server? I need the steps to reproduce this problem.

e.g.
```
getEventsDetails(eventMemberIds) {
    return new Promise((resolve, reject) => {
      let data = {
        emIds: eventMemberIds
      };

     console.log(JSON.stringify(data)); // <-- send me the console log result

      this.http.post('getEventsDetails', data).then((response: string) => {
        resolve(JSON.parse(response));
      }).catch((err) => reject(err));
    });
  }
```

btw, why do you create a new Promise? You could also do:

```
getEventsDetails(eventMemberIds) => this.http.post('getEventsDetails', data: {
  emIds: eventMemberIds
})
.then((response: string) => {
  resolve(JSON.parse(response));
});
```

**Comment by silkimen** [comment] 2018-03-02 00:46
Ok, found the issue.

But it's happening with deep structures when using "urlencoded" serializer, which is actually not officially supported by this plugin see [notice in docs #setdataserializer](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer).

![bildschirmfoto 2018-03-02 um 01 31 10](https://user-images.githubusercontent.com/4717881/36877530-f3e03a02-1dba-11e8-908a-387198ba31b0.png)

![bildschirmfoto 2018-03-02 um 01 31 53](https://user-images.githubusercontent.com/4717881/36877538-fc02a62a-1dba-11e8-8374-ec5095575561.png)

Won't handle this with high priority.

**Comment by silkimen** [comment] 2019-06-25 01:38
Won't fix this, because it's a not supported feature ([see notice in docs #setDataSerializer](https://github.com/silkimen/cordova-plugin-advanced-http#setdataserializer)).

**Closed by silkimen** 2019-06-25 01:38 UTC
Labels: bug, wontfix
