### ISSUE TITLE
[Error: advanced-http: "data" option is configured to support only following instance types: FormData] [Android.9] response type blob is not supported?

### ISSUE THREAD

**Issue by kalandher** [silkimen/cordova-plugin-advanced-http#400] opened 2021-03-05 08:24 UTC
**Describe the bug**
i'm trying to download a excel file which is in blob format, so sending responsetype as blob in sendRequest method but getting below error 

Error: advanced-http: "data" option is configured to support only following instance types: FormData.

**System info**
 - affected HTTP plugin version: 2.4.1
 - affected platform(s) and version(s): [Android.9]
 - affected device(s): MI A2
 - cordova version: 7.0.0
 - cordova platform version(s): Android 6.4.0

**Are you using ionic-native-wrapper?**
 - ionic-native-wrapper version: 4.7.0
 - did you check [ionic-native issue tracker](https://github.com/ionic-team/ionic-native/issues) for your problem?
 yes this issue not raised by any one

**Minimum viable code to reproduce**

```
  postBlob(link: string,data:any): Promise<any> {
    let url = link;
    if (baseURL) {
      url = baseURL + link;
    }
    return new Promise<any>((resolve, reject) => {
      const options = {
        method: 'post',
        responseType: 'blob',
        data: data,
        headers: requestOptions
      };
      cordova.plugin.http.sendRequest(url, options, function (response) {
        // prints 200
        resolve(response);
      }, function (response) {
        // prints 403
        console.log(response.status);
        //prints Permission denied
        console.log(response.error);
        reject(response.error);
      });
    });
  }
```

![image](https://user-images.githubusercontent.com/24358595/110088162-809b9100-7dba-11eb-8404-aea3e735f1ff.png)

**Comment by krunalsk007** [comment] 2021-05-21 08:52
what is the solution of this ?

**Comment by khelsisura** [comment] 2021-06-04 05:42
I have a same problem as of now and try everything but still not working

**Comment by russaa** [comment] 2021-06-16 20:00
First off, from the error description and the example code, it is not clear, if you are really trying to _download_ a `Blob`, or if you are trying to _upload_ a `Blob`.
The error seems to be caused by the `data` parameter which would be used for _uploading_ something.

If you are trying to upload a `Blob`, you could try to wrap it in `FormData`, e.g. see example on [developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects#creating_a_formdata_object_from_scratch).

Otherwise, if you need to upload binary data, you could try using the _raw_ data serializer:
e.g. via the option `serializer: 'raw'`

I am not sure, if this will work for sending a `Blob` though, since the documentation states, that the data must be an `Uint8Array` or an `ArrayBuffer` (I never tried it with a `Blob`).
If it does not work, maybe the `uploadFile()` method could be used instead, e.g. first storing the `Blob` data to a file and then uploading it.


If it is really for _downloading_ a `Blob`:
setting the `responseType` to `"blob"` should be enough, but I think the problem here is your `data` parameter.
You need the correct serializer depending on what the `data` is that you are sending via your `post` request.

**Comment by silkimen** [comment] 2022-03-31 01:21
Thank you @russaa for this excellent answer 😊

**Comment by silkimen** [comment] 2023-05-24 01:41
Closing this, because you didn't provide enough information. 😔 Feel free to open a new issue, if your problem still exists! 👍

**Closed by silkimen** 2023-05-24 01:41 UTC
Labels: need more info
