### ISSUE TITLE
API should support adding custom cookies

### ISSUE THREAD

**Issue by ruben82** [silkimen/cordova-plugin-advanced-http#46] opened 2017-11-20 10:11 UTC
Hi 
I'm try to send to server a request to a SMSession cookie. All works good on Android, but if I use iOS 11cannot achieve that. 
Any ideas about it? Thanks

My ionic info are

```
ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : android 6.3.0 ios 4.5.3
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.0.0 
    Node              : v7.8.0
    npm               : 4.2.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.1 Build version 9B55
```

**Comment by silkimen** [comment] 2017-11-23 20:28
Hi Ruben,
sorry for my late response. I've been busy the last days.

I didn't understand your problem. Can you describe it more detailed? Do you have some log messages?

**Comment by ruben82** [comment] 2017-11-23 21:49
Hi @silkimen thanks' for replying me.
In my app I need to send a header as Cookie called SMSession. So I added it to my code

`this.http.setHeader('cookie', 'SMSESSION=MY_SESSION_TOKEN');`

All works well on Android, in fact my HttpServletRequest on the Java server has got the cookie that plugin sent.
No cookie is sent if I do it on iOS (iOS 11), so my app does not work 'cos do not appear as authenticated.
I'm studying this pluging and I'm trying to understand how to call directly this function

`cookieHandler.setCookieFromString(url, resolveCookieString(response.headers));`

Does nobody encountered this issue?
Thanks'

**Comment by ruben82** [comment] 2017-11-24 09:13
Hi @silkimen I think there's a change to do for iOS 11
I do it in plugin code.. I'm trying to understand all steps to make a proper pull request

**Comment by silkimen** [comment] 2017-11-24 10:09
Ah ok, now I understand your problem!

Actually, it's not meant to be used like that. The header "cookie" is a special one and is handled internally. It's not meant to be set with `this.http.setHeader()`, because it will be overwritten automatically [here](https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/advanced-http.js#L130).

Atm, it's also not possible for you to call `cookieHandler.setCookieFromString()`, because it's not exposed. So basically, this is a feature request not an issue. I'll check how to implement this one, but I don't think it's a good idea to expose `setCookieFromString()` function.

Btw: how do you got it working on Android? It shouldn't be working on both, Android and iOS.

**Comment by ruben82** [comment] 2017-11-24 16:19
@silkimen I got the problem.. I try to explain even if it's very tough.
I spend all day long to got the solution.

There're two problems:
1) This plugin put cookie by through a merge header. This works fine on android but not on iOS: I have to set cookie explicitly. So I added at the file **advanced-http.js** row 169 this code

 ```
if(header === 'cookie'){
            console.log('ARRIVO');
            cookieHandler.setCookieFromString(host, value);
            return;
        }
```

2) **[Ionic http native](http://ionicframework.com/docs/native/http/)** plugin lacks a method: _setHeader(host, name, value)_
In iOS 11 is not good, you must put the host otherwise all cookie are cleared. So I added this method to **index.d.ts**  row 79 and all works fine. But I dont know how to tell ionic to fixed this lack.
```

        /**
     * Set a header for all future requests. Takes a header and a value.
     * @param host {string} The host
     * @param header {string} The name of the header
     * @param value {string} The value of the header
     */
    setHeader(host, header: string, value: string): void;
```
I hope this could help. I did a new version of this plugins if you need it.

**Comment by silkimen** [comment] 2017-11-24 18:00
@ruben82 there is no problem in this plugin, it's by design that you can't set a cookie header by using the function `setHeader()`.

Cookies do have properties which define e.g.:
* how long they are valid
* which domain they belong to

That's the reason I've decided not to allow setting cookies by just adding a header value. Otherwise it wouldn't be RFC compatible.

But I've added a new function `setCookie(url, cookie, options)`which will support your needs. It will be released in upcoming version 1.9.0. I'd recommend using this one instead of your implementation.

**Closed by silkimen** 2017-11-24 18:00 UTC
Labels: feature

**Comment by ruben82** [comment] 2017-11-27 08:35
thanks @silkimen  but if ionic/native HTTP does not expose this method, who uses ionic can't call this, can he?

**Comment by Immortalt** [comment] 2018-01-04 14:55
I also need to fully control my cookies so as to achieve some special functions.

**Comment by silkimen** [comment] 2018-01-04 15:27
@ruben82 you are right, but you'll need to open an issue in the [ionic-native repository](https://github.com/ionic-team/ionic-native) for this issue, because it's not a problem of this plugin, but a lack of implementation of the wrapper functionality.

@Immortalt this plugin does give you full control of cookies. You can programmatically add, remove and clear all cookies. Please read the API documentation.

**Comment by Immortalt** [comment] 2018-01-04 17:41
Would you please give me some example code of the function 
setCookie(url, cookie, options)?
I tryed to control my cookie for a whole day, very tired, and failed.

**Comment by ruben82** [comment] 2018-01-12 16:06
Hi @Immortalt  If you want to know how I solved my issue I write you the steps to do that:

- Go to **node_modules/ionic-native/http/index.d.ts** and add this method **_setHeader(host:string, header: string, value: string): void;_**
- Install [this plugins version ](https://drive.google.com/open?id=1nNqaqUtSaUNW4xEFX9QwlUE8ACM9fqNu)that I updated 
- Add cookie in this way  this.http.setHeader(HOST, 'cookie', "COOKIE_STRING"); 

Hope this help
