### ISSUE TITLE
How do you make a request with nested objects?

### ISSUE THREAD

**Issue by Canuckaholic** [silkimen/cordova-plugin-advanced-http#144] opened 2018-09-20 08:20 UTC
I'm trying to make a GET request using the following parameters, but I'm getting an error that it needs to be an object with strings:

```
{attendee_member_token:"8de375c1-fe2f-4f64-beb8-9b98ced5ccb8",status:{deviceToken:"46a52d56a25349e6368d43bd7c4f2f126fe8eb42d99092ed6f36f4f609ecdf08"},type:"ios"}
```

I don't have control over the API, so it's expecting status to be an object.

Here's more code (coffeescript):

```
# The options object is passed in where options.data is the object posted above

    cordova.plugin.http.setDataSerializer('json')
    cordova.plugin.http.setRequestTimeout(20)

    cordova.plugin.http[options.type](options.url, options.data, { 'Content-Type': options.contentType }, (response) =>
      # prints 200
      console.log(response.status)
      try
        response.data = JSON.parse(response.data)
        options.success(response.data)
      catch e
        console.error('JSON parsing error: ', e.message)
        options.error(e)
    , (response) =>
      # prints 403
      console.log(response.status)
      options.error(response, response.error)
    )
```

Help!

**Comment by silkimen** [comment] 2018-10-11 12:33
Hi Canuckaholic,

the problem is in this line `cordova.plugin.http[options.type](options.url, options.data, ...`.

If `options.type` equals `get`, `delete` or `head`  the second param needs to be be a query parameters object NOT a data object. The parameter object only accepts simple key value pairs (value being a string), because it's just creating HTTP query params.

e.g.:
```js
const myUrl = 'http://google.com/search';
const myParams = { q: 'test' };

// results in following URL "http://google.com/search?q=test"
cordova.plugin.http.get(myUrl, myParams, myHeaders, successHandler, errorHandler);
```

**Comment by silkimen** [comment] 2018-11-25 02:56
Closing this, feel free to open a new issue, if this won't solve your problem!

**Closed by silkimen** 2018-11-25 02:56 UTC
