### ISSUE TITLE
Native:  tried caling HTTP.get ,but the HTTP plugin is not installed

### ISSUE THREAD

**Issue by Alencan** [silkimen/cordova-plugin-advanced-http#264] opened 2019-11-02 10:02 UTC
when I tried to use ionic4 ,cordova to creat a app, I  do this 

 ionic cordova plugin add cordova-plugin-advanced-http   
and npm install @ionic-native/http   

but  I find a problem Native:  tried caling HTTP.get ,but the HTTP plugin is not installed 
on my app,what shou I do?

I have been installed  cordova-plugin-advanced-http  and config.xml also has  CordovaHttpPlugin

**Comment by supermavericks** [comment] 2019-11-05 10:07
same. do you resolve it? @Alencan

**Comment by Alencan** [comment] 2019-11-05 11:20
> same. do you resolve it? @Alencan

I resolve it , you should check config.xml when you build app, and that may didn't write in config.xml

**Comment by slothstronaut** [comment] 2019-11-19 14:29
This seems to be a bug with this plugin. When I first add the plugin it does a build properly the first time, then second time build works fine but when you open the app the plugin is missing. I've added it manually to config.xml which seems to have fixed the issue.

**Comment by silkimen** [comment] 2019-11-22 23:18
I don't think that this problem is related to the plugin itself. I can't reproduce it and I'm using this plugin in several projects. Maybe you forgot the `--save` flag while adding this cordova plugin?

**Comment by Alencan** [comment] 2019-11-23 02:17
@silkimen ,thanks,I had resolved this problem

**Comment by silkimen** [comment] 2019-11-23 02:58
Closing this, feel free to open a new issue, if this won't solve your problem! 👍

**Closed by silkimen** 2019-11-23 02:58 UTC
Labels: need more info

**Comment by pcsantana** [comment] 2019-12-18 18:47
@Alencan how did you solve id?

Thank you!

**Comment by pcsantana** [comment] 2019-12-18 20:02
Ok, I solved!
For me the problem was that the http call was made before the platform was ready! 
Thanks!
