### ISSUE TITLE
TLS connection could not be established

### ISSUE THREAD

**Issue by Adza93** [silkimen/cordova-plugin-advanced-http#225] opened 2019-06-18 09:11 UTC
Hello there,
I am experiencing issue on Android devices running ionic 3 and  with advanced-http plugin which returns more than often following error, and several other errors similar to this:

2019-06-12 13:34:16.873 619-826/ W/Cordova-Plugin-HTTP: TLS connection could not be established
    com.silkimen.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLException: Read error: ssl=0x7321595188: I/O error during system call, Software caused connection abort
        at com.silkimen.http.HttpRequest.code(HttpRequest.java:1449)
        at com.silkimen.http.HttpRequest.stream(HttpRequest.java:1740)
        at com.silkimen.http.HttpRequest.buffer(HttpRequest.java:1729)
        at com.silkimen.http.HttpRequest.receive(HttpRequest.java:1856)
        at com.silkimen.cordovahttp.CordovaHttpBase.processResponse(CordovaHttpBase.java:159)
        at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLException: Read error: ssl=0x7321595188: I/O error during system call, Software caused connection abort
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.huc.OkHttpURLConnection$NetworkInterceptor.intercept(OkHttpURLConnection.java:647)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.huc.OkHttpURLConnection$UnexpectedException$1.intercept(OkHttpURLConnection.java:582)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at okhttp3.internal.huc.OkHttpURLConnection.getResponse(OkHttpURLConnection.java:454)
        at okhttp3.internal.huc.OkHttpURLConnection.getResponseCode(OkHttpURLConnection.java:491)
        at okhttp3.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at okhttp3.internal.huc.OkHttpsURLConnection.getResponseCode(OkHttpsURLConnection.java:26)
        at com.silkimen.http.HttpRequest.code(HttpRequest.java:1447)
        at com.silkimen.http.HttpRequest.stream(HttpRequest.java:1740) 
        at com.silkimen.http.HttpRequest.buffer(HttpRequest.java:1729) 
        at com.silkimen.http.HttpRequest.receive(HttpRequest.java:1856) 
        at com.silkimen.cordovahttp.CordovaHttpBase.processResponse(CordovaHttpBase.java:159) 
        at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:74) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-06-12 13:34:26.735 619-640/ W/System: A resource failed to call close. 
2019-06-12 13:34:26.772 619-640/ W/System: A resource failed to call close. 

I think what it happens is that during the connection android system decides to switch from Wifi to Cellular  connection, and this plugin then fails on SSL handshake part of connection checks. 

Application network is configured as 

setSSLCertMode("pinned");
setDataSerializer("json");
setRequestTimeout(30);

Thank you for help! If you need any additional info, feel free to ask me.

Br,
Aleksandar

EDIT: Just to add error status code in this situations is -2, which starts separate logic on my side for notifying user about possibly expired ssl certificate. But when getting issues like this it looks to me like a false alarm.

**Comment by silkimen** [comment] 2019-06-25 00:53
Hi Aleksandar,
status code -2 is returned when an javax.net.ssl.SSLException exception occurs which indicates "some kind of error detected by an SSL subsystem." (see [Android reference for SSLException](https://developer.android.com/reference/javax/net/ssl/SSLException)).
In your case this seems to be related to an issue in OKHTTP: https://github.com/square/okhttp/issues?utf8=%E2%9C%93&q=javax.net.ssl.SSLException Please file an issue there.

**Comment by Adza93** [comment] 2019-06-25 07:06
> Hi Aleksandar,
> status code -2 is returned when an javax.net.ssl.SSLException exception occurs which indicates "some kind of error detected by an SSL subsystem." (see [Android reference for SSLException](https://developer.android.com/reference/javax/net/ssl/SSLException)).
> In your case this seems to be related to an issue in OKHTTP: https://github.com/square/okhttp/issues?utf8=%E2%9C%93&q=javax.net.ssl.SSLException Please file an issue there.

Hi there @silkimen,

Thanks for your quick reply! It seems like you are very much right about OKhttp. However, as I can see this thread https://github.com/square/okhttp/issues/4418
the issue is very old and not fixed. It looks like maintainers wont fix it because they cannot reproduce it.

Can we do anything regarding this issue to fix it on the side of cordova-plugin-advanced-http codebase?

**Comment by ashenwgt** [comment] 2019-07-02 10:19
Hi @Adza93, is the issue still present? I'm also getting the error logs with the same error code -2:
```
⚡️  [log] - -2   
⚡️  [log] - The certificate for this server is invalid. You might be connecting to a server that is pretending to be “reqres.in” which could put your confidential information at risk.   
⚡️  [log] - undefined   
```

My code is available at https://github.com/ashenwgt/ionic-capacitor-ssl-pinning

Any suggestions to get this plugin working?

**Comment by Adza93** [comment] 2019-07-02 14:27
@ashenwgt my problem is not due to invalid certificate. Your problem is because you are probably enabling ssl pinning but not providing ssl certificate to pin to. it must be exactly the same certificate as on your server that you are attempting to connect.

**Comment by Asterodeia** [comment] 2019-08-01 07:46
Hi,
The issue is still present, since I'm experiencing the same problem (the original one) working on a very bad WiFi connexion. 
Everything works fine when I use the plugin without setSSLCertMode("pinned");

**Comment by silkimen** [comment] 2019-11-22 23:34
Hi Aleksandar, unfortunately there is nothing I can do to fix your problem. It needs to be fixed in OKHttp, I'm sorry! Therefore I'm closing this to prevent more comments not related to your issue.

**Closed by silkimen** 2019-11-22 23:34 UTC

**Comment by abasit-folio3** [comment] 2020-05-15 08:58
Hi @Adza93 were you able to solve it? I am same exception but only on samsung galaxy android phones. Other than that every android phone is working perfectly exception samsung galaxy. Weired thing is before making this API, two APIs (POST and GET) are working.
